name: "Python mailer pipeline"

on:
    workflow_dispatch:

jobs:

    send_mail:
        runs-on: ubuntu-latest
        steps:
            - name: Update ubuntu
              run: sudo apt-get update

            - name: Checkout code
              uses: actions/checkout@v5.0.0

            - name: Setup python env
              uses: actions/setup-python@v5.6.0
              with:
                 python-version: '3.x'

            - name: Install dependecies
              run: |
                python -m pip install --upgrade pip

            - name: Send mail by executing python script.yp
              run: python script.py
              env:
                WORKFLOW_NAME: ${{ github.workflow }}
                REPO_NAME: ${{ github.repository }}
                WORKFLOW_RUN_ID: ${{ github.run_id}}
                SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
                SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                RECEVER_EMAIL: ${{ secrets.RECEVER_EMAIL }}